name: Deploy Worker
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        name: Build App and Deploy Cloudflare Worker
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npm run build
            - name: Deploy Cloudflare Workers
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  secrets: |
                      VITE_RECAPTCHA_SITE_KEY
              env:
                  VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
